### PR TITLE
Update: Fix dimension select search behavior

### LINKED ISSUE #344: UX issue when filtering in dimension dropdown
When I type to filter on a dimension name, the combobox list is filtered by what I've typed.

After I select what I want, the search text doesn't go away but the combobox filter is dropped and everything is shown.

### PR DESCRIPTION
**Pull request by kevinhinterlong**
Resolves #344 

## Description
The dimension search had inconsistent behavior depending on the cardinality of the dimension being search
- for low cardinality dimensions, when searching, if you clicked an option the list would be recomputed and override the actual search results
- for high cardinality dimensions, when searching, if you clicked an option the list would stay filtered as expected

## Proposed Changes
Only show dimension options if there is no search filter for low cardinality dimensions

## License

I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: packages/reports/addon/components/filter-values/dimension-select.js [hunk 1]
```diff
@@ -1,58 +1,62 @@
...
  * Licensed under the terms of the MIT license. See accompanying LICENSE.md file for terms.
  *
  * Usage:
- *   {{filter-values/dimension-select
- *       filter=filter
- *       onUpdateFilter=(action 'update')
+ *   <FilterValues::DimensionSelect
+ *       @filter={{filter}}
+ *       @onUpdateFilter={{action "update"}}
  *   }}
```
Comment (daniellevinson) [inline packages/reports/addon/components/filter-values/dimension-select.js]:
```suggestion
 *   />
```

File: packages/reports/addon/components/filter-values/dimension-select.js [hunk 2]
```diff
@@ -1,58 +1,62 @@
...
+class DimensionSelectComponent extends Component {
   /**
    * @private
    * @property {Ember.Service} _dimensionService
    */
-  _dimensionService: service('bard-dimensions'),
+  @service('bard-dimensions') _dimensionService;
 
   /**
    * @property _metadataService
```
Comment (daniellevinson) [inline packages/reports/addon/components/filter-values/dimension-select.js]:
```suggestion
    * @property {Ember.Service} _metadataService
```

File: packages/reports/addon/templates/components/filter-values/dimension-select.hbs [hunk 3]
```diff
@@ -16,8 +16,9 @@
     @extra={{hash filter=@filter}}
     @triggerComponent="power-select-bulk-import-trigger"
     @optionsComponent="power-select-collection-options"
-    @onchange={{action "setValues"}}
-    @search={{action "searchDimensionValues"}}
+    @onchange={{action this.setValues}}
+    @onclose={{set this.searchTerm undefined}}
+    @search={{action this.searchDimensionValues}}
```
Comment (daniellevinson) [inline packages/reports/addon/templates/components/filter-values/dimension-select.hbs]: `action` is not necessary I believe here and in 19?

File: packages/reports/tests/integration/components/filter-values/dimension-select-test.js [hunk 4]
```diff
@@ -148,4 +148,46 @@ module('Integration | Component | filter values/dimension select', function(hook
...
+
+    const searchTerm = '5';
+    const selectedId = '5';
+
+    this.onUpdateFilter = changeSet => {
+      set(this, 'filter', { ...this.filter, values: changeSet.rawValues });
+    };
+
+    await render(
+      hbs`<FilterValues::DimensionSelect @filter={{this.filter}} @onUpdateFilter={{action this.onUpdateFilter}} />`
```
Comment (daniellevinson) [inline packages/reports/tests/integration/components/filter-values/dimension-select-test.js]:
```suggestion
      hbs`<FilterValues::DimensionSelect @filter={{this.filter}} @onUpdateFilter={{this.onUpdateFilter}} />`
```

File: packages/reports/tests/integration/components/filter-values/dimension-select-test.js [hunk 5]
```diff
@@ -104,7 +104,9 @@ module('Integration | Component | filter values/dimension select', function(hook
       );
     };
 
-    await render(hbs`{{filter-values/dimension-select filter=filter onUpdateFilter=(action onUpdateFilter)}}`);
+    await render(
+      hbs`<FilterValues::DimensionSelect @filter={{this.filter}} @onUpdateFilter={{action this.onUpdateFilter}} />`
```
Comment (daniellevinson) [inline packages/reports/tests/integration/components/filter-values/dimension-select-test.js]:
```suggestion
      hbs`<FilterValues::DimensionSelect @filter={{this.filter}} @onUpdateFilter={{this.onUpdateFilter}} />`
```
