### PR TITLE
Fixing dashboard widget bug with cloned dashboards

### LINKED ISSUE #674: Dashboard widgets disappear when adding a new widget in a cloned dashboard.
**Describe the bug**
After adding a new widget, but not picking from an existing one, you're redirected to a dashboard that is empty or has missing widgets. When you refresh the dashboard goes back to how it was before you added the new widget.

**To Reproduce**
1. Go to an existing dashboard with multiple widgets.
2. Clone report.
3. Click on add widget and then click create new.
4. Add some metrics to the report.
5. Click 'Save Widget'.
6. You're redirected to an empty dashboard or a dashboard with missing widgets.
7. Refresh page and the dashboard returns to the state before you added the widget.

**Expected behavior**
After adding the new widget you should be redirected to your dashboard with all its widgets plus the new one you just created.

**Screenshots**
demo

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80

### PR DESCRIPTION
**Pull request by ldkge**
Resolves #674

## Description
Adding a new widget to a freshly cloned report redirects you to a dashboard with all but the first widget.
The bug appears when we set the new layout back to the dashboard, but this set was not necessary. 

## Proposed Changes

- Remove set statement and add a corresponding acceptance test.

## License

I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: packages/dashboards/tests/acceptance/dashboards-test.js [hunk 1]
```diff
@@ -662,4 +662,140 @@ module('Acceptance | Dashboards', function(hooks) {
...
+
+    // Fill out request
+    await click(
+      $('.checkbox-selector--metric .grouped-list__item:contains(Total Page Views) .grouped-list__add-icon')[0]
+    );
+
+    // Run request
+    await click('.navi-report-widget__run-btn');
+    // Regex to check that a string ends with "{uuid}/view"
+    const TempIdRegex = /\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\/view$/;
```
Comment (mattgraham1995) [inline packages/dashboards/tests/acceptance/dashboards-test.js]: Do we use this regex elsewhere? Maybe it should be in a util module and imported where it's needed.

File: packages/dashboards/tests/acceptance/dashboards-test.js [hunk 2]
```diff
@@ -662,4 +662,140 @@ module('Acceptance | Dashboards', function(hooks) {
...
+
+    widgetColumns = findAll('.navi-widget:nth-child(5) .table-header-cell').map(el => el.textContent.trim());
+
+    assert.deepEqual(
+      widgetColumns,
+      ['Date', 'Total Page Views'],
+      'Table columns for the second new widget are rendered correctly'
+    );
+
+    // hover css events are hard
```
Comment (mattgraham1995) [inline packages/dashboards/tests/acceptance/dashboards-test.js]: did you try using `triggerEvent('mouseenter'... `?

File: packages/dashboards/tests/acceptance/dashboards-test.js [hunk 3]
```diff
@@ -662,4 +662,140 @@ module('Acceptance | Dashboards', function(hooks) {
       'the filters reflect the dashboards modified filters'
     );
   });
+
+  test('New widget after clone', async function(assert) {
```
Comment (kevinhinterlong) [inline packages/dashboards/tests/acceptance/dashboards-test.js]: This test feels pretty big, maybe cut it down to just clone a dashboard, add a new widget and assert it was added instead of all the in between asserts

There's a lot of overlap with these two tests

`clone dashboard`
https://github.com/yahoo/navi/blob/7f8ebd603a6e56f1338c38039563e9e9c8bb9962/packages/dashboards/tests/acceptance/dashboards-test.js#L327-L354

`New widget`
https://github.com/yahoo/navi/blob/7f8ebd603a6e56f1338c38039563e9e9c8bb9962/packages/dashboards/tests/acceptance/dashboards-test.js#L368-L478

File: packages/dashboards/addon/routes/dashboards/dashboard/widgets/add.js [hunk 4]
```diff
@@ -31,10 +31,8 @@ export default Route.extend({
         widget.set('dashboard', dashboard);
 
         return widget.save().then(({ id }) => {
-          let layout = get(dashboard, 'presentation.layout'),
-            newLayout = this._addToLayout(layout, Number(id));
-
-          set(dashboard, 'presentation.layout', newLayout);
```
Comment (jkusa) [inline packages/dashboards/addon/routes/dashboards/dashboard/widgets/add.js]: 👍 Looking into this, we no longer need this b/c we moved away from `layout` being an array to a `fragment` (which has its own observer).

File: packages/dashboards/tests/acceptance/dashboards-test.js [hunk 5]
```diff
@@ -662,4 +662,140 @@ module('Acceptance | Dashboards', function(hooks) {
...
+
+    assert.equal(currentURL(), '/dashboards/6/view', 'Taken back to dashboard page');
+
+    assert.deepEqual(
+      widgetsAfter,
+      ['Mobile DAU Goal', 'Mobile DAU Graph', 'Mobile DAU Table', 'Untitled Widget', 'Untitled Widget'],
+      '"Untitled Widget"s are still on dashboard after navigating to subroute'
+    );
+
+    window.confirm = () => {
```
Comment (jkusa) [inline packages/dashboards/tests/acceptance/dashboards-test.js]: Can we restore this at the end of the test
