### PR TITLE
Fix: Allow save when mustHaveData is toggled (fixes #532)

### LINKED ISSUE #532: Can't save delivery rule when only updating mustHaveData toggle
**Describe the bug**
We added the feature to only send reports via email if there is data. The schedule modal did not allow users to save a delivery rule if toggling the mustHaveData toggle was the only change.

**To Reproduce**
1. Go to '/reports'
2. Click on 'schedule modal'
3. Toggle "mustHaveData" toggle
4. No option to save delivery rule

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by colemanProjects**
Resolves #532

## Description
We added the feature to only send reports via email if there is data. The schedule modal did not allow users to save a delivery rule if toggling the mustHaveData toggle was the only change.

## Proposed Changes
Make schedulingRules an ember data model fragment so that the model passed to the schedule modal actions can actually listen for each rule in the schedulingRules object.

There's a corresponding change to the schedule.js and hbs common actions that depend on this navi-core update
-

## License

I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: packages/core/addon/models/delivery-rule.js [hunk 1]
```diff
@@ -34,7 +35,11 @@ export default DS.Model.extend(Validations, {
   updatedOn: DS.attr('moment'),
   deliveryType: DS.attr('string', { defaultValue: 'report' }),
   frequency: DS.attr('string', { defaultValue: 'week' }),
-  schedulingRules: DS.attr({ defaultValue: () => {return featureFlag('enabledNotifyIfData') ? {mustHaveData: false} : {} }}),
+  schedulingRules: fragment('fragments/scheduling-rules', {
+    defaultValue: () => {
```
Comment (balajimanoharan) [inline packages/core/addon/models/delivery-rule.js]: Do we need defaultValue here, if we define defaults in the fragment?

File: packages/reports/addon/templates/components/common-actions/schedule.hbs [hunk 2]
```diff
@@ -87,7 +87,7 @@
             size="small"
             class="schedule-modal__must-have-data-toggle"
             value=localDeliveryRule.schedulingRules.mustHaveData
-            onToggle=(mut localDeliveryRule.schedulingRules.mustHaveData)}}
+            onToggle=(action "toggleMustHaveData")}}
```
Comment (balajimanoharan) [inline packages/reports/addon/templates/components/common-actions/schedule.hbs]: Can we use `toggle` instead? https://github.com/DockYard/ember-composable-helpers#toggle

File: packages/core/addon/models/delivery-rule.js (hunk 1 above)
Comment (colemanProjects) [reply packages/core/addon/models/delivery-rule.js]: we discussed this. Removed it from the fragment definition
