### PR TITLE
Fix: Stop dimension filter initial loading of large dimensions.

### LINKED ISSUE #344: UX issue when filtering in dimension dropdown
When I type to filter on a dimension name, the combobox list is filtered by what I've typed.

After I select what I want, the search text doesn't go away but the combobox filter is dropped and everything is shown.

### PR DESCRIPTION
**Pull request by Alex-Aralis**
Resolves #344 

## Description
For large dimensions you must paste the term 2 or 3 times before the value shows up in the results. In some cases it briefly flashes the value but then disappears from the results list.

## Proposed Changes
- Stop loading all dimensions on initial filter dimension selector focus for large dimensions as defined by `config.navi.searchThresholds.contains`.

## Screenshots

No initial load all on focus for large cardinality dimension:
image

Load after value input:
image

### CODE REVIEW

File: packages/reports/addon/components/filter-values/dimension-select.js [hunk 1]
```diff
@@ -42,9 +50,14 @@ export default Ember.Component.extend({
    */
   dimensionOptions: computed('filter.subject', function() {
     let dimensionName = get(this, 'dimensionName'),
-      dimensionService = get(this, '_dimensionService');
+      dimensionService = get(this, '_dimensionService'),
+      metadataService = get(this, '_metadataService');
+
+    if (get(metadataService.getById('dimension', dimensionName), 'cardinality') <= LOAD_CARDINALITY) {
+      return dimensionService.all(dimensionName);
```
Comment (daniellevinson) [inline packages/reports/addon/components/filter-values/dimension-select.js]: this works fine for low cardinality dimensions since searching also waits for `all` to resolve, right?

Comment (cythrawll) [reply packages/reports/addon/components/filter-values/dimension-select.js]: correct see: https://github.com/yahoo/navi/blob/master/packages/data/addon/services/bard-dimensions.js#L332
