### PR TITLE
Fix: Remove targetObject use and ember internals copy (fixes #296)

### LINKED ISSUE #296: targetObject is deprecated in 3.x

### LINKED ISSUE #297: '@ember/object/internals' is deprecated in 3.x

### PR DESCRIPTION
**Pull request by colemanProjects**
fixes #296 
fixes #297 

passing a target to a closure action
https://github.com/emberjs/ember.js/blob/v3.7.2/packages/%40ember/-internals/glimmer/lib/helpers/action.ts#L79

deprecated target Object
https://github.com/emberjs/ember.js/issues/14168

deprecation of ember internals copy
https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-runtime-deprecate-copy-copyable

### CODE REVIEW

File: packages/core/addon/components/pick-container.js [hunk 1]
```diff
@@ -204,7 +204,8 @@ export default Ember.Component.extend({
      */
     applyChanges(newSelection) {
       let selection = newSelection || this.get('_editableSelection');
-      this.sendAction('updateSelection', selection);
+      const update = this.get(this, 'updateSelection') || (() => {});
```
Comment (jkusa) [inline packages/core/addon/components/pick-container.js]: Can we do `const updateSelection`

**Comment by colemanProjects** [comment]
oh yea, i need to update the way we send the action via the tests
